In [1]:
import pynbody as pb
import numpy as np
import pandas as pd
import glob
import os
import h5py
import time 
import tables
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import imageio
from natsort import natsorted
import importlib.util
import sys
from pathlib import Path
from mpl_toolkits.mplot3d import Axes3D
import ast
import matplotlib.patches as patches
os.chdir('/home/takeichi/MAP/halo_tracing_code_Nithun')
import halo_trace as ht
from halo_trace import tracing
file_path = '/home/takeichi/MAP/Code_Yuma_2025/Code/star_trace_Yuma.py'
module_name = 'star_trace'

spec = importlib.util.spec_from_file_location(module_name, file_path)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

pb.config['halo-class-priority'] = ['HaloNumberCatalogue', 'AHFCatalogue',
  'AmigaGrpCatalogue',
  'VelociraptorCatalogue',
  'SubFindHDFHaloCatalogue',
  'RockstarCatalogue', 
  'SubfindCatalogue',
  'NewAdaptaHOPCatalogue',
  'NewAdaptaHOPCatalogueFullyLongInts',
  'AdaptaHOPCatalogue',
  'HOPCatalogue',
  'Gadget4SubfindHDFCatalogue',
  'ArepoSubfindHDFCatalogue',
  'TNGSubfindHDFCatalogue']

In [2]:
file_path = '/home/takeichi/MAP/Code_Yuma_2025/Code/disrupted_traceCopy_verJul14.py'
module_name = 'stdisrupt'
spec = importlib.util.spec_from_file_location(module_name, file_path)

stdisrupt = importlib.util.module_from_spec(spec)
spec.loader.exec_module(stdisrupt)

In [3]:
file_path1 = '/home/takeichi/MAP/Code_Yuma_2025/Code/making_com_cord.py'
module_name1 = 'comcord'
spec1 = importlib.util.spec_from_file_location(module_name1, file_path1)

comcord = importlib.util.module_from_spec(spec1)
spec1.loader.exec_module(comcord)

In [4]:
stdisrupt.run_star_trace_analysis(242, 4096,[138])

Working on 138
Starting full analysis for simulation 242, halo 138 from snapshot 4096...
62
Using only the following steps which contain ahf_dir and AHF catalogs:
['004096', '004032', '003936', '003840', '003744', '003648', '003606', '003552', '003456', '003360', '003264', '003195', '003168', '003072', '002976', '002880', '002784', '002688', '002592', '002554', '002496', '002400', '002304', '002208', '002112', '002088', '002016', '001920', '001824', '001740', '001728', '001632', '001536', '001475', '001440', '001344', '001269', '001248', '001152', '001106', '001056', '000974', '000960', '000864', '000776', '000768', '000672', '000637', '000576', '000480', '000456', '000384', '000347', '000288', '000275', '000225', '000192', '000188', '000139', '000107', '000096', '000071']
File will be saved as /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.004096/h242.cosmo50PLK.3072gst5HbwK1BH.004096.trace_back3_138.hdf5
grplist= [138]
simlow= /data/S

Tracing halos:   0%|          | 0/61 [00:00<?, ?step/s]

Starting step 004032
simhigh= <TipsySnap "/data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.004032/h242.cosmo50PLK.3072gst5HbwK1BH.004032" len=90232938>
Advanced step 003936
ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.004032/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.004032.0000.z0.015.AHF_
	Matching halos by merit function
207
[[19082502        0        0 ...        0        0        0]
 [       0  2108718        0 ...        0        0        0]
 [       0        0   712935 ...        0      151        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...     6756        0        0]
 [       0       24        0 ...        0        0        0]]
	Ni= [19117091  2111202   714661   460343   319940   415948   409072   236698
   386444   187419   199018   273002   103820   195218   169353   127806
   109350   103018    82312    67994

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
207
[[18631586        0        0 ...        0        0        0]
 [       0  2041399        0 ...        0        0      331]
 [       0        0   497634 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...     6579        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [18709103  2048414   721182   445545   286409   390838   396524   236699
   372720   187419   186280   264502   113976   189137   158319   124994
   106388   100477    77427    64482    93934    75292    74797    71420
    71567    70358    63738    64508    52497    64656    55947    56023
    50723    49356    36460    47268    45952    46539    38882    35369
    40086    41116    40688    38992    34678    25321    32264    32308
    31391    31370    29840    24764    31559    27730    30473    28871
    29774    28336    28403    21386    24973    24530    26822    25305
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
178
[[18729115        0        0 ...        0        0        0]
 [       0  2023881        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0     7784]]
	Ni= [18832887  2048025   312693   447117   254778   109947   400954   284736
   370688   210291   190058   128390   264564   226175   190227   141227
   126586   107786   104698    74200    94747    65059    79572    77073
    74050    71470    73359    63553    64898    64790    51808    57594
      673    56777    50834    51659    50039    45363    48017    46581
    36003    40649    41213    34037    38987    27483    35092    34091
    32406    32516    27132    31617    32776    31493    29812    28463
    30583    29026    27646    28725    24243    22845    26921    25113
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
178
[[18245372        0    68262 ...        0        0        0]
 [       0  1944017        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [18414093  1977334   390499   430076   254780   238195   388700   260811
   359086   210234   176898   108841   256890   224730   183158   143926
   122969   104967   102371    70235    94445    61201    77629    74343
    74050    68408    71311    60943    63057    64470    50888    56015
      673    55310    50249    51514    49742    42155    47030    45597
    32297    39253    40892    31569    38516    23248    34617    33899
    31984    31778    27132    30663    32759    30757    28666    27543
    30209    28139    28348    28580    23345    22669    26766    23689
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.003648/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.003648.0000.z0.113.AHF_
	Matching halos by merit function
175
[[18441606        0        0 ...        0        0        0]
 [       0  1938998        0 ...        0        0        0]
 [    5452        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [18508285  1940826   313053   434771   297780   396332   365675   223788
   355882   184753   258609   217813   259803   181999    72244   148023
   116219   106471   105328    95458    62618    78872    77661    70166
    76977    71295    74317    61755    61234    63887    64749    53339
    57267    56141    50492    44370    50389    48543    47462    46773
    43625    41081    39702    31242  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
175
[[18229737        0    24793 ...        0        0        0]
 [       0  1908037        0 ...        0        0        0]
 [    6157        0   306895 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [18320529  1910351   313052   427854   287942   390207   360444   223762
   347950   178821   255359   188898   256184   178406    71256   120309
   113989   105132   103800    95298    60966    75299    76432    69033
    76977    71622    73371    60614    61234    62940    64595    52373
    56348    55493    50238    43444    50217    48017    47467    46324
    43647    40929    38972    30289    38575    38289    30651    37085
    36386    34813    36443    31750    31898    12064    30608    27826
    30695    28509    30265    29958    25278    21923    28270    25253
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
169
[[18486319        0     6650 ...        0        0        0]
 [       0  1919947        0 ...        0        0        0]
 [    3408        0   328297 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [18512972  1921663   331705   437329   318297   410465   395304   369197
   239476   387572   188038   256424   261409   178873   127413   118866
   106351   105518    64581    96325    95749    62524    74926    78621
    70255    78239    70447    75938    65426    62496    63574    64806
     1406    56746    56519    50519    41106    50678    44572    49414
    47439    38502    41110    39294    39274    37708    37935    38369
    37833    30573    36322    35116    30911    29092    32132    32118
    28760    30916    31197    29048    30484    30203    28823    28984
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
169
[[18003595        0    15666 ...        0        0        0]
 [       0  1849326        0 ...        0        0        0]
 [    6207        0   325467 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [18061117  1852831   331674   422999   293772   401057   381625   356409
   239469   369335   176048   248102   252643   171046   120013   113316
   102958   101389    61830    95935    95625    59038    70143    75271
    64552    78239    67141    73273    65126    59933    61110    64417
     1406    53435    54903    49955    38840    50220    39307    48052
    46341    37434    40699    37767    38851    37084    37607    37821
    37690    28988    36298    34377    28788    29105    31208    31648
    27560    29415    30398    27846    30030    30204    27930    28744
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.003360/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.003360.0000.z0.197.AHF_
	Matching halos by merit function
174
[[18008932        0    13477 ...        0        0        0]
 [       0  1844554        0 ...        0        0        0]
 [    4063        0   337071 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0     8193]
 [       0        0        0 ...        0     8336        0]]
	Ni= [18070402  1846031   341134    63289   428321   434888   358173   380957
   241589   358659   182008   245759   254415   169922   134072    96548
   107710   102736    98605    97029    61650    59540    75207    79691
    66892    61049    73036    69310    51176    65662    58578      755
    64465    60621    52331    55073    50056    50470    48775    36382
    47381    40245    40703    32336  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
174
[[17500447        0    25267 ...        0        0        0]
 [       0  1779673        0 ...        0        0        0]
 [    6415        0   334693 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0     7849]
 [       0        0        0 ...     8186        0        0]]
	Ni= [17608588  1782046   341108   237955   408348   412628   358712   366690
   241591   344265   169528   237409   246734   163172   122705    91387
   105335    99161    94204    96616    59462    55812    71908    79691
    64141    58342    70703    69067    48580    59423    56185      755
    64090    58489    50442    52518    49383    49990    47377    30894
    46178    39420    40330    33996    38715    35744    38778    36592
    38109    37028    33685    33308    28068    30381    31200    25995
    26612    25178    31322    29501    27937    29682    25835    27202
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
177
[[17650408        0    16336 ...        0        0        0]
 [       0  1815015        0 ...        0        0        0]
 [    5634        0   356483 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0     8101]
 [       0        0        0 ...        0     8107        0]
 [       0        0        0 ...     8088        0        0]]
	Ni= [17744227  1815686   362117   425497   289842   418074   401345   230178
   373620   349329   181679   252716   240664   167064   128694    87708
   107938   101205    98849    93095    60635    59450    79332    83193
    58619    72514    70288    72747    71433    57334    64353    59606
    56801    52771    50055    51319    50647    48083    47829    42732
    40030    40639    39799    39618    39122    37182    36702    37165
    34433    30094    33541    29483    32741    32643    31135    31245
    32231    31627    27465    27798    24937    28309    27237    29898
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
177
[[17460176        0    23024 ...        0        0        0]
 [       0  1796449        0 ...        0        0        0]
 [    7599        0   354515 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0     8067]
 [       0        0        0 ...     8077        0        0]]
	Ni= [17610553  1797321   362114   419557   289850   412080   394324   190996
   369813   345828   177890   250050   238471   165098   136622    86448
   106939   100277    98700    91419    59985    53580    79332    83193
    57641    71484    69500    71280    70684    54070    64237    58922
    56260    52014    49882    50789    50488    47432    47405    42513
    39779    40517    39799    39558    39019    36993    36292    37006
    34005    27851    31147    29062    32720    32553    30878    30928
    32168    31495    27149    27535    24047    27909    26605    29775
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
181
[[17168754        0    42933 ...        0        0        0]
 [       0  1785206        0 ...        0        0        0]
 [   14217        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0       41        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [17252359  1786095   377555   385179   413382   401430   383556   362810
   344290   176537   174707   247238   234550   162921   129637    82757
   105239    99468    99724    87993    87339    58327    71856    54400
    85691    56746    69809    47136    65656    49340    64153    57769
    55405    50896    49747    50514    50566    47054    46552    41554
    42761      816    41458    39640    40434    39851    39000    37015
    36122    36636    33426    35631    29052    31367    32228    27400
    30828    31315    26824    31092    26666    29565    27432    24680
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
181
[[16599024        0    54019 ...        0        0        0]
 [       0  1723488        0 ...        0        0        0]
 [   15918        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0       84        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [16734297  1725590   377557   384803   394789   380656   359961   348845
   333558   156753   160242   238927   220760   156003   127474    76235
   101688    95874    99204    81972    87332    55577    69568    46477
    85691    52745    66805    62767    61531    50310    63750    55358
    53627    48448    49098    48805    49957    45190    44812    41555
    41619      816    40964    38789    39952    39752    38514    36222
    34701    35980    31806    35372    27259    30599    31878    25254
    29776    30741    24172    30552    25250    29108    26322    22204
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
174
[[16465169        0    40376 ...        0        0        0]
 [       0  1772180        0 ...        0        0        0]
 [    1327        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [16546122  1774842   433008   417449   404444   159001   377473   343181
   350712   335738   162353   244474   225484   155407   129638   102439
   102229    98437    95204    94609    78301    81696    55833    68229
    54605    66765    46938    46017    61152    59752    63926    56656
    48436    54400    48139    49535    49928    50334    45590    46227
    44928    42743    41452    41898    39155    40148    38869    36854
    35972    32826    35982    28253    26415    32468    30948    32008
    30602    30946    25804    27004    29233    29444    26431    28606
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
174
[[15877670        0    52677 ...        0        0        0]
 [       0  1694020        0 ...        0        0        0]
 [     467        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...     7523        0        0]]
	Ni= [16031418  1711156   428384   417406   381105   237353   358773   326303
   320000   319690   146363   236411   218788   144604   116561    99359
   101838    94881    95310    94609    74180    76987    53493    58046
    50646    63017    40372    64121    59301    52607    63476    54771
    46301    52560    45696    48832    48297    49622    43781    46905
    42912    41569    40546    41762    38112    39706    38340    35967
    34816    30350    35290    26443    25184    31640    28623    31517
    29453    30304    24183    23994    28651    29401    25109    28219
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.002688/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.002688.0000.z0.441.AHF_
	Matching halos by merit function
181
[[15799941        0     9395 ...        0        0        0]
 [       0  1723987        0 ...        0        0        0]
 [    5134        0   459305 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [15851139  1726084   464439   442254   382259   356620   248401   313188
   282792   324638   230024   246642   146355   174013   141671   121353
   109572   106450   102290    71939    97183    79348    56386    53228
    59300    63566    59401    61968    52106    57540    63703    52467
    53302    45955    49203    49038    50087    46652    37267    43976
    43777    42741    43852    40327  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
181
[[15230947        0    12760 ...        0        0        0]
 [       0  1614499        0 ...        0        0        0]
 [    5809        0   457013 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [15294687  1651280   462822   436202   356323   333856   215276   295288
   185090   307585   220805   235025   131731   173596   137250   109808
   109571   105868    99921    68175    93045    76043    55138    48883
    54659    60286    57333    59054    49463    56209    63234    49114
    51058    43504    48421    47164    49234    44830    34961    42470
    41931    41420    43773    39261    36927    39264    35464    37976
    31256    35823    34567    34700    23673    31292    23001    31179
    25676    28565    29605    23900    30632    28109    24717    23133
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


simhigh= <TipsySnap "/data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.002554/h242.cosmo50PLK.3072gst5HbwK1BH.002554" len=87866069>
Advanced step 002496
ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.002554/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.002554.0000.z0.500.AHF_
	Matching halos by merit function
187
[[15595953        0     1492 ...        0        0        0]
 [       0  1694807        0 ...        0        0        0]
 [    1195        0   471024 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [15602727  1704696   472219   450927   370509   343318   319810   237857
   292962   223477   250038   213251   140954   180460   149089   128717
   112856   111581   107059    96246    67201    83163   

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
187
[[15245920        0     3116 ...        0        0        0]
 [       0  1652489        0 ...        0        0        0]
 [    2055        0   468253 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [15256940  1655960   470308   445905   355600   331189   310651   216423
   282678   216184   241466   210815   132348   175361   145437   121590
   112806   111075   105296    93605    66418    79400    62939    52291
    54483    53551    57823    59271    61301    56071    63511    47842
    51930    45458    48701    41162    49731    47235    47439    45676
    39352    43703    41725    41846    42915    39446    39301    36435
    37977    35846    31406    36419    35356    31867    28996    31551
    31817    20679    23710    30893    29623    28598    28885    25504
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.002400/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.002400.0000.z0.574.AHF_
	Matching halos by merit function
196
[[15034535        0     3118 ...        0        0        0]
 [       0  1623190        0 ...        0        0        0]
 [    1010        0   471782 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [15042312  1677088   472792   446817   345154   315887   306061   273440
   181579   198405   215143   235971   211428   125257   137300    87427
   115613   113307   116210   106909    91716    78540    56520    50744
    18918    55583    56841    60938    22129    63396    44996    54978
    45745    51279    48428    44431    49572    38109    46245    45517
    43181    40949    41132    36806  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
196
[[14542391        0     6213 ...        0        0        0]
 [       0  1511834        0 ...        0        0        0]
 [    1495        0   468393 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...     6568        0        0]]
	Ni= [14555492  1610312   469888   438919   322531   311159   289442   258476
   216185   167526   204076   221963   206098   112322   130865    83461
   105557   112047   115636   102985    87180    72904    52463    45264
    13174    50866    54328    57943    26068    62787    41174    53311
    43561    48609    47317    42140    48593    31946    43909    43317
    41080    39318    38939    34573    38813    38436    34169    34544
    36689    31342    34517    24899    34604    34743    30838    32427
    31294    29386    26602    28304    29911    25243    28520    23497
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.002208/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.002208.0000.z0.678.AHF_
	Matching halos by merit function
193
[[14948311        0     4156 ...        0        0        0]
 [       0  1605462        0 ...        0        0        0]
 [    1487        0   479664 ...        0        0        0]
 ...
 [       0        0        0 ...        0     6931        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [14961772  1652326   481151   461176   325148   335847   299677   206048
   253078   195076   219128   166824   209241   114035   100973   140466
   108407   117246   123867   113255    92465    87911    67032    45468
    54579    50989    59162    63184    46360    42751    53248    48008
    49515    47581    46649    49166    44306    43794    41621    40256
    41465    39665    38205    35126  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
193
[[13571589   816262        0 ...        0        0        0]
 [       0        0  1492841 ...        0        0        0]
 [    2977        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [14409859  1546501   479336   459487   300823   321460   284944   172572
   240105   192806   204204   143566   201570   102470   101905   129946
    88051   115436   123869   117126    84549    83230    63043    38899
    51572    43945    55592    62571    43769    41179    50567    43331
    47188    46350    34264    47882    41892    42536    39353    38457
    40903    37949    37534    33947    35645    33125    32868    34504
    35525    29811    29243    20072    34787    29134    29989    31518
    30217    20706    29036    27024    25751    20615    26204    23253
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


simhigh= <TipsySnap "/data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.002088/h242.cosmo50PLK.3072gst5HbwK1BH.002088" len=85820570>
Advanced step 002016
ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.002088/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.002088.0000.z0.750.AHF_
	Matching halos by merit function
184
[[14456254    44729        0 ...        0        0        0]
 [   12196   817156        0 ...        0        0        0]
 [       0        0  1634008 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0     7891        0]
 [       0        0        0 ...        0        0     7502]]
	Ni= [14506321   829352  1638020   529125   505587   372299   319950   299883
   159683   252740   207849   166370   209059   119385   116977   138210
   134841   121664   121008   102757   108788    80354   

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
178
[[14067834    83500        0 ...        0        0        0]
 [   24219   838329        0 ...        0        0        0]
 [       0        0  1469905 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [14172014   862548  1515909   504482   509551   355884   301406   289130
   243328   202475   155183   200180      833   104287   109772   126943
   127855   120072   121326    62148    73641    83553    57306    74999
    55006    53055    38957    64011    57617    59440    45166    40977
    48811    47870    46741    42560    48492    45765    46502    42435
    40492    40497    38291    34133    38628    35092    37383    36704
    35702    35553    33411    32641    24791    31672    27983    32001
    31697    29956    30933    29979    29239    26188    27008    26542
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.001920/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.001920.0000.z0.862.AHF_
	Matching halos by merit function
165
[[12753630  1333883    55516 ...        0        0        0]
 [   62554        2   861403 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...     8838        0        0]
 [       0        0        0 ...        0     8612        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [14196247   923959  1364315   515575   485113   302916   279644   281332
   238446   195683   149575   196024    89375   103947   111701   122459
   118026   124700   117010    63587    79871    63284    39320    46786
    51615    64814    55448    56286    34223    40640    47048    32851
    43340    48104    46035    47616    47161    35807    40129    40996
    39351    38979    37280    39511  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
165
[[11606067  1682262    85891 ...        0        0        0]
 [  101588      223   821951 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0     8109]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [13476969   923797  1275244   531060   487342   278402   250709   263075
   228846   185806   128398   188972    79457    90649   106140   115794
   113780   124779   116932    61491    73672    56982    50082    39287
    48575    65113    51067    52052    29395    33730    42498    32056
    40303    44894    44544    45961    45186    33645    37165    38518
    36476    36701    35071    39371    30721    31337    36104    35273
    34029    33015    29875    29410    33940    27448    30118    30839
    27256    21544    27809    27097    26803    25189    27963    23291
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.001740/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.001740.0000.z1.000.AHF_
	Matching halos by merit function
-1
[[12084884   244714    71655 ...        0        0        0]
 [   66495  1623290        0 ...        0        0        0]
 [   73212        0   844434 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [     228       61        0 ...        0        0        0]]
	Ni= [12612636  1692112   918801  1045306   626777   502729   188679   264380
   305362   246684   238139     1903   182814   184607   140352    98506
   140690   117854    75874   115197    98790    70393    63694    72321
    71412    34503    49166    58584    46657    52685    44823    40521
    45386    42375    32717    46783    46142    44793    43607    41506
    28392    38501    30971    36369   

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[11897115   267045    82342 ...        0        0        0]
 [   73691  1613393        0 ...        0        0        0]
 [   73779        0   843615 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [     179       42        0 ...        0        0        0]]
	Ni= [12485831  1689770   918730  1031185   626434   503109   171978   259407
   303109   242789   235343    51452   196648   183185   136694    96737
   140685   116817    74536   114706    97498    75781    62705    71553
    71412    33499    48694    58315    45431    52142    44164    40214
    45170    41971    31145    46051    45869    44557    43386    41378
    17547    37886    30858    35978    36585    37529    31530    29881
    35264    31947    36353    35309    34169    29906    32850    33059
    32549    30097    30679    29616    28706    29319    28031    27028
  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.001632/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.001632.0000.z1.094.AHF_
	Matching halos by merit function
-1
[[11059309   144786   145217 ...        0        0        0]
 [  151230  1729588        0 ...        0        0        0]
 [   18552        0   907447 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [11548037  1881859   925999   976915   745227   598525   242559   295275
   230017   222627   118757   140899   166587   178046    94540   144335
   113274    99012   113358    70653    70756    72965    67189    47917
    74608    32881    46489    57647    50609    41248    41067    39171
    44550    44842    44087    42939    40125    41654    36886    36180
    36013    34149    34789    28812   

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[10010559   164539   279739 ...        0        0        0]
 [  318164  1558613        0 ...        0        0        0]
 [   14682      202   908418 ...        0        0        0]
 ...
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]
 [       0        0        0 ...        0        0        0]]
	Ni= [10684580  1878618   923302   906427   659320   591450   219946   274440
   202751   205940   117749   127641   158714   167119    78733   143919
   104805    89241   107443    61985    43626    62058    61143    37891
    74261    32442    42894    55407    46718    37520    37327    37086
    42552    42836    41931    40753    35787    39870    33974    33159
    36452    31573    32049    25328    36009    30614    22890    23267
    33450    32258    32671    25436    24063    31826    30021    30493
    26888    25833    25309    27381    29954    25403    28282    25832
  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[9987863  183795   67195 ...       0       0       0]
 [  79848 1682726       0 ...       0       0       0]
 [  21225       0 1170140 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0   14318]]
	Ni= [10265210  1762574  1191365   936443   777368   619938   279736   209005
   210545   199855   135136   175777   150340   168845    96055    88850
   112541   108714    69623    74396        0    81226    66388    67736
    62590    34374    36390    43887    56036    41183    49731    43459
    44244    42598    33322    40857    40915    38886    36489    35672
    38418    29194    26091    35443    33831    33887    34096    34291
    32905    33047    33298    30963    31565    32552    30372    30925
    26700    27307    20812    27988    28357    26604    26406    24130
    24547    21624    23263    25678  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[9427715  323819   87989 ...       0       0    2512]
 [  57681 1690892       0 ...       0       0       0]
 [  29427       0 1154711 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...   14040       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [9880592 1748588 1184138  908385  764804  615799  270279  231011  202048
  192471  125528  171088  146751  167441   89316   95248  110617  104645
   66023   58906   70236   80522   52697   66607   62404   34541   31274
   42519   54944   39721   48316   42411   43548   41621   30634   39990
   39829   37637   35097   34260   37987   28193    2424   34415   32689
   32768   33073   33762   32168   32353   32701   29759   30646   31744
   30271   30150   25346   26178   26826   26968   27727   25812   24644
   22777   23058   21463   20448   25225   24437   23444   24058   22359
   23025   22677   19816   21234   153

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[8475172  283257   45265 ...       0       0       0]
 [   5636 2041710       0 ...       0       0       0]
 [ 105746       0 1179470 ...       0       0       0]
 ...
 [      0       0       0 ...   14320       0       0]
 [      0       0       0 ...       0       0       0]
 [    127       0       0 ...       0       0       0]]
	Ni= [8834585 2049718 1285216  793239  755116  643242  180343  253434  194587
  183546  170512   98652   82032  171539   73733  114121  111225   96217
   61602   78799   81530   79822   52734   57253   17061       0   39991
   52660   48069   35953   50745   40906   42821   39589   38963   38340
   35317   36604   37940   37760   33551   36801       0   31564   33106
   32543   31744   29789   33325   31671   29799   32360   31207   31630
   30809   27780   29090   28941   26235   26355   27250   26642   24565
   24699   23032   22937   25553   23379   21037   17535   22103   22953
   22836    4275   20113   21947   206

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[7824040  296781   42224 ...       0       0       0]
 [   8542 1987754       0 ...       0       0       0]
 [ 262046       0 1002880 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [     55       0       0 ...       0       0       0]]
	Ni= [8322502 1999629 1264927  717945  719775  618120  160080  233840  178688
  171663  160337   79245  114001  167461   25160  102311  105176   88801
   52773   65617   70755   77646   26522   58407   38520   11608   36438
   50070   44082   31111   50948   38532   40771   37174   36379   36147
   32739   36477   37714   36102   31163   34866       0   28732   30560
   30158   29355   27409   31929   29541   27435   30073   29349   30106
   29535   25338   26892   26989   24002   24535   25896   25075   22422
   22823   17249   20370   24022   21819   18785   18075   20486   21581
   21295   12438   17943   20422   207

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[8271055      70   33673 ...       0       0       0]
 [    108 2411130       0 ...       0       0       0]
 [  35285       0 1052192 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [8346095 2572338 1088118  856825  761629  756066  134927  245685  164989
  203016  198783  171746  178589  102962  115525   99967   75981   94928
   59488   72592   81009   59625    9537   57205   54002   50887   37877
   48302   49100   44057   40975   43117   40591   38823   38643   38489
   37447   33047   33121   33799   33112   33997   30211   33383   30306
   30065   32486   31135   31735   31388   31298   30637   27859   29761
   30017   28925   28376   28401   27429   27429   26250   27219   25555
   23477   25722   16825   21021   23535   24377     692   18746   21092
    4997   22308   22130   22550   209

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[7147939     850  307826 ...       0       0       0]
 [     51 1859431       0 ...       0       0       0]
 [   5331       0 1085018 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...   17113       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [7610356 2185073 1091676  783611  696737  580406  134908  222249   85073
  175486  177754  144167  170115  116576   99971   74421   45480   85104
   47168   68463   76878   45420   33810   49636       0   46782   33500
   46861   44185   43080   37651   40030   36935   36204   35348   35527
   34615   29274   29885   31261   29758   31296   27702   29482   24899
   24164   28531   28898   29312   28683   29514   27528   23486   27602
   30175   26292   25222   25794   25297   23073   22209   24921   25555
   20563   22955       0   14730   19620   21940   11993   13981   17534
    4997   19965   19479   20378   184

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.001106/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.001106.0000.z1.749.AHF_
	Matching halos by merit function
-1
[[6914426       0   30172 ...       0       0       0]
 [      0 1800572       0 ...       0       0       0]
 [   1054       0 1489743 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [7235323 1803509 1491066  728472  696010  489989  283401  262620  232677
  208382  167758  144736  173426  116024   98720   59532   84127   79785
   66423   77473   38604   48334   46742   53988   41234   49752   49998
   33987   46613   47049   39118   40086   36810   37970   37002   36892
   24390   34945   34785   33163   33071   31163   31848   30316   29721
   30111   31073   30345   26641   30428   30946   14985   27009   28873
  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[6446304       0   31749 ...       0       0       0]
 [      0 1696408       0 ...       0       0       0]
 [   1038       0 1437345 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0   15041       0]]
	Ni= [6817080 1701258 1438995  643811  658015  448025  264525  260651  217888
  192608  151578  134411  167055   33069   91277   44409   76543   71645
   52540   75053   29080   42239   43533   49104   35399   47849   48935
   31383   44618   43821   37152   38420   34598   36793   35093   34866
   24438   33439   33635   33128   31519   31105   30269   28460   27058
   22333   28286   28750   22690   28114   29965       5   25447   27191
   26550   29237   26924   26563   26733   23285   22790   21852   24128
   21335   24722   18432   14030   20695   23730   20592   19972   23842
   21223   20846   22121   18697      

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[5615799       0    2635 ...       0       0       0]
 [      0 1620961       0 ...       0       0       0]
 [      0       0 1439510 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [6110904 1621243 1440056  626862  407583  403340  242606  153022  225886
  184133  159285  148901  161199  128208  117574  108381   82723   61528
   71621   72399   14287   51710   40355   51363   41959   52064   29513
   43452   46164   26188       0   22781   41046   43714   40033   27837
   39753   36702   28567   37890   34379   34899       0   33857   33085
   32766   30491   29423   25498   28726   25385   29884   27436   28182
   27741   28831   26983   22759   24466   26410   25457   26684   24989
   22030   19996   23145   23650   20775   20700   18827   12838   22464
   21753   18953   20847   19025   193

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[5488557       0    3920 ...       0       0       0]
 [      0 1592874       0 ...       0       0       0]
 [      0       0 1416646 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [5995873 1597504 1417355  616053  399580  390977  239406  153022  221738
  175972  159521  148880  159148  124213  113655  108379   80314   60453
   70280   71439   26880   51488   38835   50403   41287   52003   28396
   42946   45626   25102       0   21632   40734   43403   38305   26789
   38931   35988   25479   37365   33627   33750       0   33315   32501
   32374   30258   29060   24574   28278   24680   29469   27022   26177
   27307   28443   26381   21407   24455   25983   24697   26337   24358
   21371   19427   22768   23108   20394   20676   18026   12240   22261
   21015   18284   20417   18032   190

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[4664187       0       0 ...       0       0       0]
 [      0       0 1455188 ...       0       0       0]
 [      0 1358903       0 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...   13890       0       0]]
	Ni= [4910150 1456242 1359982  579509  490172  318837  340004  224639  227068
  184338  191926  137034  132671  148246   97245  108954   74095   72060
   67166   65614   52702   34419   46850   33472   43550   40129   27998
   44622   45936   40753   31636   40248   38155   34883   32320   17080
   33632   27645   26471   32278   30434   29210   22181   31020   28077
   29003   26619   26255   25632   25224   26521   24697   25212   25254
   19746   27000   19589   26665   24387   21345   22242   22947   22186
   21484   21261   15772   17854   13151   18399   19307   10119   18916
   17138   15775   19109   17657   103

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[3583986     443       0 ...    4496       0       0]
 [      0       0 1316359 ...       0       0       0]
 [      0 1274818       0 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [4073766 1317515 1277683  532308  467588  284115  294637  195591  212263
  183489  156685   80310  130680  135255   80723   83852   66712   66791
   61950   61362   47437   25292   46779   21798   37668   35598   18375
   41395   42341   36950   19721   36098   32117   30554   25296   13184
   30278   21650   18959   24309   24737   21937   19312   28187   23246
   20032   22581   21891   20388   22185   26946   21727       0   12823
   18385   23286   13794   23788   19922   19478   19634   18784   20620
   18884   19089       0   14243       0   15231   16342    6813   17482
   14964   12016   17628   15481    74

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000768/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.000768.0000.z2.524.AHF_
	Matching halos by merit function
-1
[[3772266       0       0 ...       0       0       0]
 [      0 1634708       0 ...       0       0       0]
 [      0       0 1511107 ...       0       0       0]
 ...
 [     90       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [3779151 1635569 1511107  637888  535161  352222  367324  309575  276108
  251122  206940  161365  163410  151251   91247  100670   77440   77911
   74139   71464   66672   49099   52867   50715   40946   39474   43805
   43681   36675   37028   38294   30502   31995   29076   33150   31180
   27484   25760   20151   17723   24593   25481   26547   25584   24472
   21694   24400   25194   24641   21535   23334   22321   24500   22467
  

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[2600350       0       0 ...       0       0       0]
 [      0 1364718       0 ...       0       0       0]
 [      0       0 1285561 ...       0       0       0]
 ...
 [    154       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [2974610 1389395 1285561  534778  468964  298384  283328  249571  254036
  210624  171964  152582  104693  133212   76360   72383   53838   66778
   63409   58149   58276   42485   43219   39885   35740   34179   35886
   34780   36208   29177   28532   22832   30046   21928   28256   26371
   20210   13694   15442   13152   19215   21218   12627   16041   17751
   15805   19575   19234   19137   14592   18556   16723   19477   16965
   17425   17729   16436   13187   20188   17545   18148   18151   17133
   16446   14765   13741   12228   13478       0       0   11218   15606
    5903   12128     113   14712   134

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[2541089       0       0 ...       0       0       0]
 [      0 1335248       0 ...       0       0       0]
 [      0       0 1163592 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0   11963]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [2573835 1351598 1288028  505157  454765  313391  272100  256748  259349
  258165  206212  175155  155158  148345   86303   79999   68581   63015
   62258   59367   52335   52342   48315   44564   41605   42219   36580
   35876   44391   37783   18766   33824   29562   25612   29269   29012
       0   27009   14767   17453   12832   20006   17077   21054   20646
   20842   19139   19466   20692   19564   16167   19266   18847   13130
   19308   18627   14198   17848   16928   17381   18941   16503   13525
   18301   11448   16736   12622   15926   14828   15540   14543   15278
   14063   15437   14511       0   122

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[2100694       0       0 ...       0       0       0]
 [      0       0  848248 ...       0       0       0]
 [      0 1035423       0 ...       0       0       0]
 ...
 [      0       0       0 ...   10078       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [2171156 1109384 1150646  392868  407970  284735  232268  221548  235977
  190278  163842  151307  169263  128248   74127   62410   58420   38143
   55265   52513   47268   38187   46678   36762   34190   40102   30863
   32063   39039   30513   16676   32990   24888   19469   23362   25495
       0   23990       0   12943    8274   17569   10059   18386   17851
   20531   16548   17183   16414   13960   14454   15315   15624   12251
   16464   14510   12850   14429   10453   16538   16086       0   12228
   15987       0   14248    9953   12725   11447   12658   12286   12687
   11730   13816   12971       0      

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000480/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.000480.0000.z3.831.AHF_
	Matching halos by merit function
-1
[[888532      0      0 ...      0      0      0]
 [     0 673815      0 ...      0      0      0]
 [     0      0 536716 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [1279418  790028  594270  300903  278052  208907  185692  213662  196268
  170818  131319  112598  130871   81338  107854   99225   93924   66154
   48456   50227   28884   40919   48498   44683   30516   40754   35569
   36011   28049   32828   19968   25475   15960   27429   24797   27880
   24825   25920   20209   12778   21850   19351   16956   20931   11513
       0       0   18183   16415   15184   13588   15534    8703   15646
   10201   13423   11831   12609   127

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[767105      0 478299 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0 481755      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [1330702  704855  540593  287789  264650  199671  161966  207532  187742
  163044  124821  105529  122683   78118  106741   92512   87457   60096
   43177   48020   16806   38615   45861   42404   29647   44881   35508
   34675   26601   29525   18384   21343   16316   25032   23285   27094
   24565   23675   18849   12006   20407   17458   16249   19789   10155
       0       0   15415   16302   14668   12969   14013    8175   15091
       0   12625   10477       0   11798   12157       0   13248    6562
   11061   12896    9619       0    9279    8921    5104    8772       0
    7446       0    7436       0    9367       0    8406       0   11608
 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[529383      0      0 ...      0      0      0]
 [     0 434795      0 ...      0      0      0]
 [  8719      0      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0   5878]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0   4924      0]]
	Ni= [552185 435766 364523 380580 192093 224062 194002 161721 158581 160301
 106869 123113 102452 105794  92413  86314  66330  66958  66767  49435
  41852  45859  40913  41587  37082  33031  40327  31841  25884  25195
  29559  26059  21451  27318  18725  11943  25461  23645  19580  21995
  10107  25221  21741   9697  10005  16644  15216  16504  17312  16023
  12343   9705  11819  15169  14218  14196   9077   7312   9379    587
  11463  12091   7220  11423  10516  10644   8380      0   7383      0
   9335      9   9386      0   9145   8277   7754   7322      0   8639
      0   8181   3947   7723   6038      0   7320      0   7076   6238
   6659   6985   70

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[423831      0      0 ...      0      0      0]
 [     0 390853      0 ...      0      0      0]
 [ 14529      0      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [472536 391889 302862 358660 162652 189387 183751 129782 142054 151263
  82206 114335  90530  93762  81937  72110  63748  59086  28660  42329
  31820  40898  35552  34509  29713  29879  36878  27154  24295  19181
  25866  18004  22313  23265  16975  10495  21345  22315  17674  20929
   8973  23107      0   6799   6564  14570  13874  14696  15637  10890
   9514   7628      0  13416  11553  13552   7850      0   8028      0
  10135  11539      0  10537   6821   9613   7154      0   6513      0
   8107     14      0      0   8408   7277   7418   5534      0   7730
      0   7529   2626      0      0      0   6154      0   6387   6193
      0   7143     

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


simhigh= <TipsySnap "/data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000288/h242.cosmo50PLK.3072gst5HbwK1BH.000288" len=75329861>
Advanced step 000275
ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000288/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.000288.0000.z5.782.AHF_
	Matching halos by merit function
-1
[[339140      0      0 ...      0      0      0]
 [     0      0 214388 ...      0      0      0]
 [     0 307844      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [358010 322106 307844      0 163582 132500 117309  90938 102523  60703
  81056  85606  70073  40688      0  63463      0  53901  44868  39005
  33152  34967  32469  30650  17169  26280  22079   9430  20056  15537
  19576  22690  17903  21205  23767      0   1897  14699  16746

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[     0      0      0 ...      0      0      0]
 [     0 178587      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [ 18497 274015      0      0 154508 122774 110448  73931  92753      0
  82072  81067  63982      0      0  59186  44853  51862  42317  36680
  32159  34494  30744  28174  13112  24489  21035   9360  18928  10860
  18913  21498  17647  20587  22337      0      0  13764  14753  17437
  10715      0  14087  14107   9843  12696   6350  10370   7878  10794
  11096   9235  11009   8970  12309   5903   8645   5221      0   6238
   5869   7404   8618   7125   4828   4941   6799   5561   5561   6264
   5341   6536   6130      0   5589      0      0   5259   4918   4794
      3   6296   4821   5469      0   5328   5254      0      0   4424
   4661   4513   47

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000225/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.000225.0000.z6.984.AHF_
	Matching halos by merit function
-1
[[    0     0     0 ...     0     0     0]
 [    0     0 90255 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
	Ni= [     0 129627     10  56960  61042  53054  47850  62450  53605  49047
  39211  45337  38469  29879  31052  26870  27141  26412      0  23421
  18532  18938  14522  15796  16901      0  15145  17372      0  10739
  13676   8862   8218   7461  10717   9137   4763   8904  10146   7178
   9094   6769   7322   4507   3598   2136   8375   5483   6669   4647
   4510   4749   5356   5903   3723   3582   4712   4309   4020      0
   3668   4685   4300   4235   3887   4242   4461   3034      0   3329
   4324   4249 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[    0     0     0 ...     0     0     0]
 [    0     0 74059 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
	Ni= [107920 111814  49014  49654  41235  33843  44585  47028  41408  46046
  25035  42235  30676  19420  19732  17868  19208      0  10964  20931
  12485  14593   6807  11290  15036   7065  14451  11351   7115   6016
  12739   7966   6634   4357   8849   8895   3323   8049   8766   3722
   8697   5368   6679      0      0      0   4821   5225   6421      0
   3083   3777   4728   5231   2772      0      0   3460   3170      0
      0      0      0      0   4860   3457   3106   2895      0      0
   2884      0   4436      0   3844      0   3075   2946      0      0
   2473      0      0      0      0      0   2462   3117      0      0
      0   2597      0      0      0      0      0      

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000188/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.000188.0000.z7.986.AHF_
	Matching halos by merit function
-1
[[145805      0      0 ...      0      0      0]
 [     0  88505      0 ...      0      0      0]
 [     0      0  76039 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [145951  88505  76039  59232  59797  53139  50166  51854  49729  46462
  40839  42455  38616  37911  34564  34387  29954  28395  24256  25708
  24336  18337  14173  16646  16054  16196  16097  16977  15263  15178
  10225  12886  10887  12554  11028  10769   8055  10668  10935  11021
   9564   9637   8929   9305   9213   9211   8918   7948   7960   6244
   5360   7109   6334   5072   5905   6032   6595   5427   6813   5692
   4543   5323   5360   5432   5166   5407   5770 

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
-1
[[74984     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0 45384     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...  1237     0     0]
 [    0     0     0 ...     0     0     0]]
	Ni= [75180 40083 45384 20264 40298 33791 24941 31632 27484 20852 23059 16688
 19352 23357 19638 15664     0 14163 13914 17948 22729 11706  2634  9713
  6725  9119 12644 12660  9157  8515  9638  8129  2188  7583  9330  2882
     0     0  6137  7369  2601     0  1950  4922  4892     0  5625  1432
  3339  3771  1295  3798  4005  2542     0     0  2231  1880  1891  2855
  2204  1513  2448  2156     0  2020  4332  4104     0  1978     0  2054
  2434     0     0     0     0     0  2071     0     0     0     0  2123
  1578  1374  1637     0     0  1544  1616     0     0  1475  1605     0
     0     0  1237     0]
	Nj= [74984 45384 40298 38836 33791 22729 31632 27484 23059 24938 23357 19115
 17948

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000107/ahf_200/h242.cosmo50PLK.3072gst5HbwK1BH.000107.0000.z11.992.AHF_
	Matching halos by merit function
-1


/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)
pynbody.halo : Unable to load AHF substructure file; continuing without. To expose the underlying problem as an exception, pass ignore_missing_substructure=False to the AHFCatalogue constructor


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
	Ni= [    0     0     0     0     0 13337     4 14790     0     0     0  7734
     0     0     0     0 10010     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
  3216  3281     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0  1050     0     0     0
     0     0     0     0  1209  1146     0     0   739     0     0     0
     0     0   908     0     0     0     0     0     0     0     0     0
     0     0   365     0]
	Nj= [14790 13337 10010  7734  3216  3281  1209  1050     0     0     0   739
     0     0     0     0     0     0     4     0     0     0     0     0
   635   120     0     0     0     0     0     0     0   511     0     0
     0     0     0     0     0     0   43

pynbody.halo : Unable to load AHF substructure file; continuing without. To expose the underlying problem as an exception, pass ignore_missing_substructure=False to the AHFCatalogue constructor


	Matching halos by merit function
-1


/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)
pynbody.halo : Unable to load AHF substructure file; continuing without. To expose the underlying problem as an exception, pass ignore_missing_substructure=False to the AHFCatalogue constructor


[[   0    0 6886 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0 8349    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
	Ni= [6886 1192 8349    0    0 2612 1218  357  888  792  571    0  677  565
  665  558  440  456    0  531  473  507  501  465  411  432  464  443
  382  454  405    0  409  253  368  378  315  360  346  386  313  313
  337  321  319  305  269  298  314  288  259  276  242    0  265  263
  269  273  202  215    0    0    0    0  258  206  229  220    0  224
  225    0  196  216  219    0  195  195    0  209  207  211  251    0
    0    0    0  214    0    0    0  178  189  182  199    0  193  199
    0  193]
	Nj= [   0 8349 6886    0 2612    0 1192 1218  888  792  571  665  558  565
  677  501  465  382  456  440  368  298  464  454  531  405    0  473
  443  346  432  386  409  411  305  314  321  378    0  360  319  313
  357  251    0  265  337  313  315  263

/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:81: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)
/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:279: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[nan]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[mask, step[-6:]] = df2.loc[mask, step[-6:]]
/home/takeichi/MAP/halo_tracing_code_Nithun/halo_trace/tracing.py:294: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->floating,key->block1_values] [items->Index(['000071'], dtype='object')]

  df.to_hdf(save_file, key='ids')
/home/takeichi/MAP/Code_Yuma_2025/Code/disrupted_traceCopy_verJul14.py:109: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot

62
Using only the following steps which contain ahf_dir and AHF catalogs:
['004096', '004032', '003936', '003840', '003744', '003648', '003606', '003552', '003456', '003360', '003264', '003195', '003168', '003072', '002976', '002880', '002784', '002688', '002592', '002554', '002496', '002400', '002304', '002208', '002112', '002088', '002016', '001920', '001824', '001740', '001728', '001632', '001536', '001475', '001440', '001344', '001269', '001248', '001152', '001106', '001056', '000974', '000960', '000864', '000776', '000768', '000672', '000637', '000576', '000480', '000456', '000384', '000347', '000288', '000275', '000225', '000192', '000188', '000139', '000107', '000096', '000071']
File exists: /data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.004096/h242.cosmo50PLK.3072gst5HbwK1BH.004096.trace_back3_138.hdf5
Aborting
--- finished tracing halo id of disrupted halo ---
halos_grpNow=[138]
looking to see if files exist for these halos
no 

/home/takeichi/MAP/Code_Yuma_2025/Code/disrupted_traceCopy_verJul14.py:109: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->floating,key->block1_values] [items->Index(['000071'], dtype='object')]

  disruptedhaloid.to_hdf(disruptedhalo_trace_files, key='df', mode='w')


working on halo:138
halo index at current snapshot: 110
data_sucessfully_saved
wrote 16 stars
loading snapshot: 002016
halo_indices[start+c+0]=np.int64(110)
halo_indices[start+c+1]=np.int64(110)
starting snapshot: 001920
ending snapshot: 002016
halo=138
f.keys()=<KeysViewHDF5 ['001920']>
last_iteration_key='001920' i.e particle data from last snapshot saved
len(last_iord)=16
halo_index: 110
len(h_i.s['iord'])=16
bridge succesfully made
len(x_i)=16
len(h_ix)=0
stars being saved for halo 110 this snapshot: 16
data_sucessfully_saved
moving on to next halo
...
loading snapshot: 002088
halo_indices[start+c+0]=np.int64(110)
halo_indices[start+c+1]=np.int64(119)
starting snapshot: 002016
ending snapshot: 002088
halo=138
f.keys()=<KeysViewHDF5 ['001920', '002016']>
last_iteration_key='002016' i.e particle data from last snapshot saved
len(last_iord)=16
halo_index: 119
len(h_i.s['iord'])=16
bridge succesfully made
len(x_i)=16
len(h_ix)=0
stars being saved for halo 119 this snapshot: 16
data_suc

IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (1800, 900) to (1808, 912) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


Processing: Frame 28/28

--- Video creation complete ---
Video saved to '/home/takeichi/MAP/Results/242/004096_138/star_distribution_movie004096138.mp4'.
Step 4 finished
-----------------

 Analysis complete for simulation 242, halo 138.
Find your results in: /home/takeichi/MAP/Results/242/004096_138


In [ ]:
/data/Sims/h242.cosmo50PLK.3072g/h242.cosmo50PLK.3072gst5HbwK1BH/h242.cosmo50PLK.3072gst5HbwK1BH.000288/h242.cosmo50PLK.3072gst5HbwK1BH.000288.trace_back3.hdf5